version: 2
jobs:
  build:
    docker: # use docker executor type; machine ans macos executors are also supported
      - image: circleci/node:8.9 # primary container, where  your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "start installing npm"
      - run: npm install # run echo command
      - run: CI=true npm run build
  test:
    docker: # use docker executor type; machine ans macos executors are also supported
      - image: circleci/node:8.9 # primary container, where  your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing project" # run echo command
      - run: npm install
      - run: npm run test
  hithere:
    docker: # use docker executor type; machine ans macos executors are also supported
      - image: circleci/node:8.9 # primary container, where  your job's commands are run
    steps:
      - checkout
      - un: echo "Hi there"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
# ok